import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { Shield, ScanSearch, Brain, BarChart3, ArrowRight, Zap, Lock, Eye } from "lucide-react";
import Navbar from "@/components/Navbar";
import GlassCard from "@/components/GlassCard";

const FEATURES = [
  {
    icon: ScanSearch,
    title: "Deployment Analysis",
    desc: "Verify if the project is actually deployed and running — not just a slide deck.",
  },
  {
    icon: Brain,
    title: "AI Authenticity Check",
    desc: "Detect whether code was genuinely engineered or generated by AI tools.",
  },
  {
    icon: BarChart3,
    title: "Stack Verification",
    desc: "Compare claimed tech stack against what's actually detected in the build.",
  },
];

const STATS = [
  { value: "Beta", label: "Stage" },
  { value: "Testing", label: "Verification Model" },
  { value: "Growing", label: "Dataset" },
];


export default function Landing() {
  return (
    <div className="min-h-screen bg-background">
      <Navbar />

      {/* Hero */}
      <section className="relative pt-32 pb-20 px-4 overflow-hidden">
        {/* Gradient orbs */}
        <div className="absolute top-20 left-1/4 w-96 h-96 bg-primary/10 rounded-full blur-[120px] pointer-events-none" />
        <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-accent/10 rounded-full blur-[120px] pointer-events-none" />

        <div className="container mx-auto text-center relative z-10">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-secondary text-secondary-foreground text-sm font-medium mb-8"
          >
            <Zap className="w-4 h-4 text-primary" />
           AI-Powered Hackathon Verification


          </motion.div>

          <motion.h1
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.1 }}
            className="text-5xl md:text-7xl font-bold tracking-tight leading-tight max-w-4xl mx-auto"
          >
            We don't judge projects.{" "}
            <span className="gradient-text">We verify builders.</span>
          </motion.h1>

          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.25 }}
            className="mt-6 text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto leading-relaxed"
          >
           BuildProof analyzes deployments and project structure to help judges
           understand how much of a project is actually implemented.
           This is an experimental prototype and results may evolve.

          </motion.p>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.4 }}
            className="mt-10 flex flex-col sm:flex-row items-center justify-center gap-4"
          >
            <Link
              to="/submit"
              className="gradient-bg text-primary-foreground px-8 py-3.5 rounded-xl text-base font-semibold hover:opacity-90 transition-all glow inline-flex items-center gap-2"
            >
              Evaluate a Project <ArrowRight className="w-4 h-4" />
            </Link>
            <Link
              to="/leaderboard"
              className="px-8 py-3.5 rounded-xl text-base font-semibold border border-border hover:bg-secondary transition-colors"
            >
              View Leaderboard
            </Link>
          </motion.div>
        </div>
      </section>

      {/* Demo snippet */}
      <section className="container mx-auto px-4 pb-20">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="glass-card gradient-border rounded-2xl p-6 md:p-8 max-w-3xl mx-auto font-mono text-sm"
        >
          <div className="flex items-center gap-2 mb-4">
            <div className="w-3 h-3 rounded-full bg-suspicious" />
            <div className="w-3 h-3 rounded-full bg-warning" />
            <div className="w-3 h-3 rounded-full bg-success" />
            <span className="ml-2 text-muted-foreground text-xs">buildproof-analysis.log</span>
          </div>
          <div className="space-y-2 text-muted-foreground">
            <p><span className="text-primary">→</span> Scanning deployment at <span className="text-foreground">hackteam.vercel.app</span>...</p>
            <p><span className="text-success">✓</span> Application is live — response: <span className="text-foreground">247ms</span></p>
            <p><span className="text-success">✓</span> Backend detected: <span className="text-foreground">Node.js / Express</span></p>
            <p><span className="text-warning">⚠</span> Claimed: TensorFlow — <span className="text-warning">Not detected in build</span></p>
            <p><span className="text-success">✓</span> Database layer: <span className="text-foreground">PostgreSQL confirmed</span></p>
            <p><span className="text-primary">→</span> Generating authenticity index...</p>
            <p className="pt-2 text-foreground font-semibold">
              Result: <span className="text-success">GENUINE BUILD</span> — Score: <span className="text-success">87/100</span>
            </p>
          </div>
        </motion.div>
      </section>

      {/* Features */}
      <section className="container mx-auto px-4 pb-20">
        <div className="grid md:grid-cols-3 gap-6">
          {FEATURES.map((f, i) => (
            <GlassCard key={i} transition={{ delay: i * 0.1 }}>
              <div className="gradient-bg rounded-lg p-2.5 w-fit mb-4">
                <f.icon className="w-5 h-5 text-primary-foreground" />
              </div>
              <h3 className="text-lg font-semibold mb-2">{f.title}</h3>
              <p className="text-sm text-muted-foreground leading-relaxed">{f.desc}</p>
            </GlassCard>
          ))}
        </div>
      </section>

      {/* Stats */}
      <section className="container mx-auto px-4 pb-20">
        <div className="glass-card rounded-2xl p-8 flex flex-col md:flex-row items-center justify-around gap-8">
          {STATS.map((s, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, scale: 0.9 }}
              whileInView={{ opacity: 1, scale: 1 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.15 }}
              className="text-center"
            >
              <div className="text-3xl md:text-4xl font-bold gradient-text">{s.value}</div>
              <div className="text-sm text-muted-foreground mt-1">{s.label}</div>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Trust bar */}
      <section className="container mx-auto px-4 pb-20">
        <div className="flex flex-wrap items-center justify-center gap-6 text-muted-foreground text-sm">
          <div className="flex items-center gap-2"><Lock className="w-4 h-4" /> End-to-end encrypted</div>
          <div className="flex items-center gap-2"><Eye className="w-4 h-4" /> Transparent scoring</div>
          <div className="flex items-center gap-2"><Shield className="w-4 h-4" /> Early access prototype </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-border py-8 text-center text-sm text-muted-foreground">
        <p>© 2026 BuildProof. Verify with confidence.</p>
      </footer>
    </div>
  );
}
